#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
import os
from pathlib import Path
from typing import List, Dict

from passage_normalization import canonicalize_text_ref, extract_text_ref_tokens

ROOT = Path('/Users/georgeandraws/workspace/coptic-lectionary-research')
OUT = ROOT / 'out' / 'data'
VAULT = Path('/Users/georgeandraws/Library/CloudStorage/GoogleDrive-georgeandraws@gmail.com/My Drive/HermesAI/obsidian-vault/Hermes/04-Reference/Coptic Orthodox Lessons/References/Lectionary')


def env_flag(name: str) -> bool:
    return os.environ.get(name, '').strip().lower() in {'1', 'true', 'yes', 'on'}


DISABLE_VAULT_PUBLISH = env_flag('LECTIONARY_DISABLE_VAULT_PUBLISH')

SOURCE_ST_BISHOY_PAGE = 'https://saintbishoy.ca/service-books/'
ROWS: List[Dict[str, str]] = [
    {
        'service_family': 'wedding_crowning',
        'service_variant': 'holy_matrimony_main',
        'section': 'main_readings',
        'reading_type': 'pauline',
        'raw_ref': 'Ephesians 5:22-6:3',
        'source_title': 'The Holy Matrimony Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Wedding_Ceremony.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main crowning rite Pauline reading.',
    },
    {
        'service_family': 'wedding_crowning',
        'service_variant': 'holy_matrimony_main',
        'section': 'main_readings',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 19:5; Psalm 128:3',
        'source_title': 'The Holy Matrimony Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Wedding_Ceremony.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (18) 19:5 and Psalm (127) 128:3 in the rite book.',
    },
    {
        'service_family': 'wedding_crowning',
        'service_variant': 'holy_matrimony_main',
        'section': 'main_readings',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 19:1-6',
        'source_title': 'The Holy Matrimony Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Wedding_Ceremony.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main crowning rite Gospel reading.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'mother_absolution_male_child',
        'section': 'part_1',
        'reading_type': 'pauline',
        'raw_ref': 'Hebrews 1:8-12',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Absolution for the woman if she bore a male child.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'mother_absolution_male_child',
        'section': 'part_1',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 32:1-2',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm 31 in LXX numbering.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'mother_absolution_male_child',
        'section': 'part_1',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 2:21-35',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Absolution for the woman if she bore a male child.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'mother_absolution_female_child',
        'section': 'part_2',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 7:12-14',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Absolution for the woman if she bore a female child.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'mother_absolution_female_child',
        'section': 'part_2',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 45:9; Psalm 45:13',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm 44:12 in the Arabic line plus 45:9,13 in English/Coptic formatting; preserve the two verse references explicitly.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'mother_absolution_female_child',
        'section': 'part_2',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 10:38-42',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Absolution for the woman if she bore a female child.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'sanctification_of_baptismal_water',
        'section': 'part_3',
        'reading_type': 'pauline',
        'raw_ref': 'Titus 2:11-3:7',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main baptismal-water sanctification readings.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'sanctification_of_baptismal_water',
        'section': 'part_3',
        'reading_type': 'catholic',
        'raw_ref': '1 John 5:5-20',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main baptismal-water sanctification readings.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'sanctification_of_baptismal_water',
        'section': 'part_3',
        'reading_type': 'acts',
        'raw_ref': 'Acts 8:26-39',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main baptismal-water sanctification readings.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'sanctification_of_baptismal_water',
        'section': 'part_3',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 32:1-2',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm 31 in LXX numbering.',
    },
    {
        'service_family': 'baptism',
        'service_variant': 'sanctification_of_baptismal_water',
        'section': 'part_3',
        'reading_type': 'gospel',
        'raw_ref': 'John 3:1-21',
        'source_title': 'Baptism and Chrismation Rite',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Baptism.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main baptismal-water sanctification readings.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'first_prayer',
        'section': 'first_prayer',
        'reading_type': 'catholic',
        'raw_ref': 'James 5:10-20',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'First prayer uses Catholic Epistle rather than Pauline.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'first_prayer',
        'section': 'first_prayer',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 6:1-2',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'First prayer Psalm.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'first_prayer',
        'section': 'first_prayer',
        'reading_type': 'gospel',
        'raw_ref': 'John 5:1-17',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'First prayer Gospel.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'second_prayer',
        'section': 'second_prayer',
        'reading_type': 'pauline',
        'raw_ref': 'Romans 15:1-7',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second prayer Pauline.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'second_prayer',
        'section': 'second_prayer',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 102:1-2',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalms (101) 102:1-2.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'second_prayer',
        'section': 'second_prayer',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 19:1-10',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second prayer Gospel.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'third_prayer',
        'section': 'third_prayer',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 12:28-13:8',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third prayer Pauline.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'third_prayer',
        'section': 'third_prayer',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 38:1-2',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (37) 38:1-2.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'third_prayer',
        'section': 'third_prayer',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 10:1-8',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third prayer Gospel.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'fourth_prayer',
        'section': 'fourth_prayer',
        'reading_type': 'pauline',
        'raw_ref': 'Romans 8:14-21',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Fourth prayer Pauline.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'fourth_prayer',
        'section': 'fourth_prayer',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 51:1-2',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (50) 51:1-2.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'fourth_prayer',
        'section': 'fourth_prayer',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 10:1-9',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Fourth prayer Gospel.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'fifth_prayer',
        'section': 'fifth_prayer',
        'reading_type': 'pauline',
        'raw_ref': 'Galatians 2:16-20',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Fifth prayer Pauline.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'fifth_prayer',
        'section': 'fifth_prayer',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 142:7',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (141) 142:7.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'fifth_prayer',
        'section': 'fifth_prayer',
        'reading_type': 'gospel',
        'raw_ref': 'John 14:1-19',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Fifth prayer Gospel.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'sixth_prayer',
        'section': 'sixth_prayer',
        'reading_type': 'pauline',
        'raw_ref': 'Colossians 3:12-17',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Sixth prayer Pauline.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'sixth_prayer',
        'section': 'sixth_prayer',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 4:1',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Sixth prayer Psalm.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'sixth_prayer',
        'section': 'sixth_prayer',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 7:36-50',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Sixth prayer Gospel.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'seventh_prayer',
        'section': 'seventh_prayer',
        'reading_type': 'pauline',
        'raw_ref': 'Ephesians 6:10-18',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Seventh prayer Pauline.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'seventh_prayer',
        'section': 'seventh_prayer',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 25:18; Psalm 25:20',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (24) 25:18,20.',
    },
    {
        'service_family': 'unction_of_the_sick',
        'service_variant': 'seventh_prayer',
        'section': 'seventh_prayer',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 6:14-18',
        'source_title': 'The Unction of the Sick',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Unction_of_Sick.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Seventh prayer Gospel.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'men_main',
        'section': 'part_1',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 15:1-23',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main funeral service for men.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'men_main',
        'section': 'part_1',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 65:4',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (64) 65:4.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'men_main',
        'section': 'part_1',
        'reading_type': 'gospel',
        'raw_ref': 'John 5:19-29',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main funeral service for men.',
    },

    # Palm Sunday readings: vespers, procession stations, matins continuation, and Divine Liturgy.
    {
        'service_family': 'palm_sunday',
        'service_variant': 'vespers',
        'section': 'vespers',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 118:26-27',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Vespers Psalm for Palm Sunday; printed as Psalm (117) 118:26-27.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'vespers',
        'section': 'vespers',
        'reading_type': 'gospel',
        'raw_ref': 'John 12:1-11',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Vespers Gospel for Palm Sunday.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_01_main_sanctuary',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 104:4; Psalm 138:1',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 1: Main Sanctuary; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_01_main_sanctuary',
        'reading_type': 'gospel',
        'raw_ref': 'John 1:43-51',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 1: Main Sanctuary; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_02_holy_virgin_st_mary',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 87:3,5,7',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 2: The Holy Virgin St. Mary; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_02_holy_virgin_st_mary',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 1:39-56',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 2: The Holy Virgin St. Mary; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_03_archangel_gabriel',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 34:7-8',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 3: The Archangel Gabriel; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_03_archangel_gabriel',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 1:26-38',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 3: The Archangel Gabriel; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_04_archangel_michael',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 103:20-21',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 4: The Archangel Michael; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_04_archangel_michael',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 13:44-53',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 4: The Archangel Michael; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_05_st_mark_evangelist',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 68:11-12',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 5: St. Mark the Evangelist; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_05_st_mark_evangelist',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 10:1-12',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 5: St. Mark the Evangelist; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_06_holy_apostles',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 19:3-4',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 6: The Holy Apostles; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_06_holy_apostles',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 10:1-8',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 6: The Holy Apostles; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_07_st_george',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 97:11-12',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 7: St. George; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_07_st_george',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 21:12-19',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 7: St. George; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_08_st_antony',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 68:35; Psalm 68:3',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 8: St. Antony; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_08_st_antony',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 16:24-28',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 8: St. Antony; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_09_northern_door',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 84:1-2',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 9: Northern Door; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_09_northern_door',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 13:22-30',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 9: Northern Door; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_10_baptismal_font',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 29:3-4',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 10: Baptismal Font; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_10_baptismal_font',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 3:13-17',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 10: Baptismal Font; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_11_southern_door',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 118:19-20',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 11: Southern Door; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_11_southern_door',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 21:1-11',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 11: Southern Door; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_12_st_john_the_baptist',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 52:8',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 12: St. John the Baptist; Psalm before the station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'procession',
        'section': 'procession_station_12_st_john_the_baptist',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 7:28-35',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday procession station 12: St. John the Baptist; station Gospel.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'matins',
        'section': 'matins',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 68:19; Psalm 68:35',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Matins Psalm after Palm Sunday procession; printed as Psalm (67) 68:19,35.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'matins',
        'section': 'matins',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 19:1-10',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Matins Gospel after Palm Sunday procession, Zacchaeus reading.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'liturgy_readings',
        'reading_type': 'pauline',
        'raw_ref': 'Hebrews 9:11-28',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday Divine Liturgy Pauline reading.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'liturgy_readings',
        'reading_type': 'catholic',
        'raw_ref': '1 Peter 4:1-11',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday Divine Liturgy Catholic Epistle.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'liturgy_readings',
        'reading_type': 'acts',
        'raw_ref': 'Acts 28:11-31',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday Divine Liturgy Praxis / Acts reading.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'first_gospel',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 81:3; Psalm 81:1; Psalm 81:2',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'First Psalm for Palm Sunday before the first Liturgy Gospel; printed as Psalm (80) 81:3,1,2.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'first_gospel',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 21:1-17',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'First Gospel for Palm Sunday Divine Liturgy.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'second_gospel',
        'reading_type': 'gospel',
        'raw_ref': 'Mark 11:1-11',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second Gospel for Palm Sunday Divine Liturgy.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'third_gospel',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 19:29-48',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third Gospel for Palm Sunday Divine Liturgy.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'fourth_gospel',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 65:1-2',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Psalm before the fourth Gospel for Palm Sunday; printed as Psalm (64) 65:1,2.',
    },
    {
        'service_family': 'palm_sunday',
        'service_variant': 'liturgy',
        'section': 'fourth_gospel',
        'reading_type': 'gospel',
        'raw_ref': 'John 12:12-19',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Fourth Gospel for Palm Sunday Divine Liturgy.',
    },
    {
        'service_family': 'general_funeral',
        'service_variant': 'palm_sunday_general_funeral',
        'section': 'prophecy',
        'reading_type': 'old_testament',
        'raw_ref': 'Ezekiel 37:1-14',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'General Funeral prayed after Palm Sunday liturgy before Holy Pascha; prophecy reading in the Palm Sunday book.',
    },
    {
        'service_family': 'general_funeral',
        'service_variant': 'palm_sunday_general_funeral',
        'section': 'main_readings',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 15:1-27',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday General Funeral Pauline from the Palm Sunday book; extends beyond the separate men_main funeral book reading.',
    },
    {
        'service_family': 'general_funeral',
        'service_variant': 'palm_sunday_general_funeral',
        'section': 'main_readings',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 65:4-5',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (64) 65:4-5 in the Palm Sunday General Funeral section.',
    },
    {
        'service_family': 'general_funeral',
        'service_variant': 'palm_sunday_general_funeral',
        'section': 'main_readings',
        'reading_type': 'gospel',
        'raw_ref': 'John 5:19-29',
        'source_title': 'Rites and Readings of Palm Sunday, Procession and General Funeral',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Palm_Sunday_And_General_Funeral_Readings_Procession.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Palm Sunday General Funeral Gospel from the Palm Sunday book.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'men_passion_week',
        'section': 'at_burial_site_override',
        'reading_type': 'old_testament',
        'raw_ref': 'Genesis 50:4-25',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Passion Week burial-site override. The rite explicitly says the Trisagion, Gospel litany, Psalm, and Gospel are then read as before.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_main',
        'section': 'part_2',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 15:39-49',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main funeral service for women.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_main',
        'section': 'part_2',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 116:7-8',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (114) 116:7-8.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_main',
        'section': 'part_2',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 26:6-13',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main funeral service for women.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_passion_week',
        'section': 'at_burial_site_override',
        'reading_type': 'old_testament',
        'raw_ref': 'Genesis 23:1-20',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Passion Week burial-site override for women; followed by Genesis 24:1-67 and then the Psalm/Gospel as before.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_passion_week',
        'section': 'at_burial_site_override',
        'reading_type': 'old_testament',
        'raw_ref': 'Genesis 24:1-67',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second Passion Week burial-site reading for women.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_delivery_main',
        'section': 'part_3',
        'reading_type': 'old_testament',
        'raw_ref': 'Isaiah 26:9-20',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Funeral for women who depart during delivery.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_delivery_main',
        'section': 'part_3',
        'reading_type': 'pauline',
        'raw_ref': 'Romans 5:1-15',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Funeral for women who depart during delivery.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_delivery_main',
        'section': 'part_3',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 78:38-39',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (77) 78:38-39.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_delivery_main',
        'section': 'part_3',
        'reading_type': 'gospel',
        'raw_ref': 'John 16:20-23',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Funeral for women who depart during delivery.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_delivery_passion_week',
        'section': 'at_burial_site_override',
        'reading_type': 'old_testament',
        'raw_ref': 'Genesis 23:1-20',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Passion Week burial-site override for women who depart during delivery; followed by Genesis 24:1-67 and then the Psalm/Gospel as before.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'women_delivery_passion_week',
        'section': 'at_burial_site_override',
        'reading_type': 'old_testament',
        'raw_ref': 'Genesis 24:1-67',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second Passion Week burial-site reading for women who depart during delivery.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'male_children_main',
        'section': 'part_4',
        'reading_type': 'pauline',
        'raw_ref': '1 Thessalonians 4:13-18',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Funeral service for male children.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'male_children_main',
        'section': 'part_4',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 27:10; Psalm 116:6',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalms (26) 27:10 and (114) 116:6.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'male_children_main',
        'section': 'part_4',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 7:11-16',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Funeral service for male children.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'male_children_at_burial_site',
        'section': 'at_burial_site',
        'reading_type': 'old_testament',
        'raw_ref': '1 Kings 17:17-24',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'At the burial site for male children.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'female_children_main',
        'section': 'part_5',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 15:50-58',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Funeral service for female children.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'female_children_main',
        'section': 'part_5',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 39:12-13',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (38) 39:12-13.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'female_children_main',
        'section': 'part_5',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 9:18-26',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Funeral service for female children.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'female_children_passion_week',
        'section': 'at_burial_site_override',
        'reading_type': 'old_testament',
        'raw_ref': 'Judges 11:30-40',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Passion Week burial-site override for female children.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'third_day_and_memorials',
        'section': 'part_6',
        'reading_type': 'pauline',
        'raw_ref': 'Romans 5:6-15',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third-day and other memorial prayers.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'third_day_and_memorials',
        'section': 'part_6',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 38:21-22',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (37) 38:21-22.',
    },
    {
        'service_family': 'funeral',
        'service_variant': 'third_day_and_memorials',
        'section': 'part_6',
        'reading_type': 'gospel',
        'raw_ref': 'John 11:38-45',
        'source_title': 'The Funeral Prayers',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Readings_Funeral_Updated.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third-day and other memorial prayers.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'first_prostration',
        'section': 'main_readings',
        'reading_type': 'old_testament',
        'raw_ref': 'Deuteronomy 5:23-33; Deuteronomy 6:1-3',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'First Pentecost prostration prophecy; summary page identifies the exact section.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'first_prostration',
        'section': 'main_readings',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 12:28-31; 1 Corinthians 13:1-12',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'First Pentecost prostration Pauline from the rite summary.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'first_prostration',
        'section': 'main_readings',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 97:7-8; Psalm 97:1',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm 97:7,8,1 in the rite book.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'first_prostration',
        'section': 'main_readings',
        'reading_type': 'gospel',
        'raw_ref': 'John 17:1-26',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'First Pentecost prostration Gospel.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'second_prostration',
        'section': 'main_readings',
        'reading_type': 'old_testament',
        'raw_ref': 'Deuteronomy 6:17-25',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second Pentecost prostration prophecy from the rite summary.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'second_prostration',
        'section': 'main_readings',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 13:13-14:17',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second Pentecost prostration Pauline; exact line confirmed in the rite book.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'second_prostration',
        'section': 'main_readings',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 115:12-13',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second Pentecost prostration Psalm.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'second_prostration',
        'section': 'main_readings',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 24:36-53',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Second Pentecost prostration Gospel.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'third_prostration',
        'section': 'main_readings',
        'reading_type': 'old_testament',
        'raw_ref': 'Deuteronomy 16:1-18',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third Pentecost prostration prophecy; exact section confirmed in the rite book.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'third_prostration',
        'section': 'main_readings',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 14:18-40',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third Pentecost prostration Pauline from the rite summary.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'third_prostration',
        'section': 'main_readings',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 66:4; Psalm 72:11',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third Pentecost prostration Psalm; exact line confirmed in the rite book.',
    },
    {
        'service_family': 'pentecost_prostration',
        'service_variant': 'third_prostration',
        'section': 'main_readings',
        'reading_type': 'gospel',
        'raw_ref': 'John 4:1-24',
        'source_title': 'Rites of the Prayers of Prostration',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Prostrations.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Third Pentecost prostration Gospel; exact line confirmed in the rite book.',
    },
    {
        'service_family': 'cornerstone_prayer',
        'service_variant': 'main',
        'section': 'foundation_cornerstone',
        'reading_type': 'old_testament',
        'raw_ref': 'Genesis 28:10-31',
        'source_title': 'Rites of Consecrations',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/consecrations-ar-en-cop.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Foundation cornerstone prophecy for a new church.',
    },
    {
        'service_family': 'cornerstone_prayer',
        'service_variant': 'main',
        'section': 'foundation_cornerstone',
        'reading_type': 'pauline',
        'raw_ref': 'Hebrews 9:1-10',
        'source_title': 'Rites of Consecrations',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/consecrations-ar-en-cop.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Foundation cornerstone Pauline.',
    },
    {
        'service_family': 'cornerstone_prayer',
        'service_variant': 'main',
        'section': 'foundation_cornerstone',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 127:1; Psalm 122:1-2',
        'source_title': 'Rites of Consecrations',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/consecrations-ar-en-cop.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Foundation cornerstone Psalm set printed before the Gospel reading.',
    },
    {
        'service_family': 'cornerstone_prayer',
        'service_variant': 'main',
        'section': 'foundation_cornerstone',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 9:28-35',
        'source_title': 'Rites of Consecrations',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/consecrations-ar-en-cop.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Foundation cornerstone Gospel.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'vespers',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 23:5-6',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Printed as Psalm 22:5-6 in source numbering; quote matches Psalm 23:5-6 in modern numbering.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'vespers',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 23:50-56; Luke 24:1-12',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Vespers Gospel on the Day of Consecration.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'matins',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 51:12-13',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Printed as Psalm 50:12-13 in source numbering; quote matches Psalm 51:12-13 in modern numbering.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'matins',
        'reading_type': 'gospel',
        'raw_ref': 'Mark 16',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Matins Gospel printed as Mark chapter 16 whole.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'liturgy',
        'reading_type': 'pauline',
        'raw_ref': 'Hebrews 9:11-28; Hebrews 10:1-24',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Pauline for the Day of Consecration.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'liturgy',
        'reading_type': 'catholic',
        'raw_ref': '1 John 4:7-21; 1 John 5:1-21',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Catholic Epistle for the Day of Consecration; visual extraction indicates 1 John 5:1-21 despite OCR noise.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'liturgy',
        'reading_type': 'acts',
        'raw_ref': 'Acts 13:13-49',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Acts / Praxis for the Day of Consecration.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'liturgy',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 45:7-8',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Printed as Psalm 44:10-11 in source numbering; quote matches Psalm 45:7-8 in modern numbering.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'liturgy',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 89:20-21',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Printed as Psalm 88:14-15 in source numbering; quote matches Psalm 89:20-21 in modern numbering.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'consecration_day',
        'section': 'liturgy',
        'reading_type': 'gospel',
        'raw_ref': 'John 19:38-42; John 20:1-18',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 34-37',
        'notes': 'Liturgy Gospel for the Day of Consecration.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_1',
        'section': 'matins',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 51:7-8',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'Printed as Psalm 50:7-8 in source numbering; quote matches Psalm 51:7-8.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_1',
        'section': 'matins',
        'reading_type': 'gospel',
        'raw_ref': 'John 1:18-42',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'Morning Gospel for first week day 1.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_1',
        'section': 'liturgy',
        'reading_type': 'pauline',
        'raw_ref': 'Hebrews 7:26-28; Hebrews 8; Hebrews 9:1-10',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 1 Pauline.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_1',
        'section': 'liturgy',
        'reading_type': 'catholic',
        'raw_ref': '1 Peter 3:8-22; 1 Peter 4:1-11',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 1 Catholic Epistle.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_1',
        'section': 'liturgy',
        'reading_type': 'acts',
        'raw_ref': 'Acts 18:24-28; Acts 19:1-20',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 1 Acts / Praxis.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_1',
        'section': 'liturgy',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 132:1',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 1 liturgy psalm; source numbering preserved as printed.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_1',
        'section': 'liturgy',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 26:6-13',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 1 liturgy Gospel.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_2',
        'section': 'matins',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 28:3-4',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 2 morning psalm; source numbering preserved as printed.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_2',
        'section': 'matins',
        'reading_type': 'gospel',
        'raw_ref': 'John 3:22-36; John 4:1-2',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 2 morning Gospel.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_2',
        'section': 'liturgy',
        'reading_type': 'pauline',
        'raw_ref': 'Hebrews 1:1-14; Hebrews 2:1-4',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 2 Pauline.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_2',
        'section': 'liturgy',
        'reading_type': 'catholic',
        'raw_ref': '1 Peter 1:10-25; 1 Peter 2:1-10',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 2 Catholic Epistle.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_2',
        'section': 'liturgy',
        'reading_type': 'acts',
        'raw_ref': 'Acts 2:22-47; Acts 3:1-10',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 2 Acts / Praxis.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_2',
        'section': 'liturgy',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 129:2-5',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 2 liturgy psalm; source numbering preserved as printed.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_2',
        'section': 'liturgy',
        'reading_type': 'gospel',
        'raw_ref': 'Mark 14:3-9',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 2 liturgy Gospel.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_3',
        'section': 'matins',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 31:1-2',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 3 morning psalm; source numbering preserved as printed.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_3',
        'section': 'matins',
        'reading_type': 'gospel',
        'raw_ref': 'John 3:1-21',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 3 morning Gospel.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_3',
        'section': 'liturgy',
        'reading_type': 'pauline',
        'raw_ref': 'Titus 2:11-15; Titus 3:1-7',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 3 Pauline.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_3',
        'section': 'liturgy',
        'reading_type': 'catholic',
        'raw_ref': '1 John 5:5-13',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 3 Catholic Epistle.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_3',
        'section': 'liturgy',
        'reading_type': 'acts',
        'raw_ref': 'Acts 8:26-39',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 3 Acts / Praxis.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_3',
        'section': 'liturgy',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 65:1; Psalm 65:6',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 3 liturgy psalm.',
    },
    {
        'service_family': 'myron_consecration',
        'service_variant': 'first_week_day_3',
        'section': 'liturgy',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 28:16-20',
        'source_title': 'Meron and Galileon Rite (Arabic)',
        'source_url': 'https://copticbook.wordpress.com/wp-content/uploads/2023/06/meron-and-galileon-ar.pdf',
        'source_page': 'OCR + visual extraction from pages 35-37',
        'notes': 'First week day 3 liturgy Gospel.',
    },
    {
        'service_family': 'home_blessing',
        'service_variant': 'main',
        'section': 'main_readings',
        'reading_type': 'pauline',
        'raw_ref': 'Romans 8:14-21',
        'source_title': 'Rites of Blessing Houses',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Blessing_Houses.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main Pauline for house blessing.',
    },
    {
        'service_family': 'home_blessing',
        'service_variant': 'main',
        'section': 'main_readings',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 102:1-2',
        'source_title': 'Rites of Blessing Houses',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Blessing_Houses.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm 102:1-2.',
    },
    {
        'service_family': 'home_blessing',
        'service_variant': 'main',
        'section': 'main_readings',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 19:1-10',
        'source_title': 'Rites of Blessing Houses',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Blessing_Houses.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main Gospel for house blessing.',
    },
    {
        'service_family': 'liturgy_of_the_waters',
        'service_variant': 'epiphany_laqan',
        'section': 'main_readings',
        'reading_type': 'pauline',
        'raw_ref': '1 Corinthians 10:1-13',
        'source_title': 'Rites of Laqan for the Feast of Theophany (Epiphany)',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Laqan_Epiphany.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main Pauline for the Epiphany Laqan / waters rite.',
    },
    {
        'service_family': 'liturgy_of_the_waters',
        'service_variant': 'epiphany_laqan',
        'section': 'main_readings',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 114:3; Psalm 114:5',
        'source_title': 'Rites of Laqan for the Feast of Theophany (Epiphany)',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Laqan_Epiphany.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm 114 (113):3,5.',
    },
    {
        'service_family': 'liturgy_of_the_waters',
        'service_variant': 'epiphany_laqan',
        'section': 'main_readings',
        'reading_type': 'gospel',
        'raw_ref': 'Matthew 3:1-17',
        'source_title': 'Rites of Laqan for the Feast of Theophany (Epiphany)',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Laqan_Epiphany.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main Gospel for the Epiphany Laqan / waters rite.',
    },
    {
        'service_family': 'church_consecration',
        'service_variant': 'main',
        'section': 'part_1',
        'reading_type': 'pauline',
        'raw_ref': 'Hebrews 9:1-10',
        'source_title': 'Rites of Consecration of Churches, Altars and Vessels',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Book-2_Consecration.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main Pauline in church consecration section.',
    },
    {
        'service_family': 'church_consecration',
        'service_variant': 'main',
        'section': 'part_1',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 127:1; Psalm 122:1-2',
        'source_title': 'Rites of Consecration of Churches, Altars and Vessels',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Book-2_Consecration.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Printed as Psalm (126) 127:1 and Psalm (121) 122:1,2.',
    },
    {
        'service_family': 'church_consecration',
        'service_variant': 'main',
        'section': 'part_1',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 9:28-35',
        'source_title': 'Rites of Consecration of Churches, Altars and Vessels',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Book-2_Consecration.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main Gospel in church consecration section.',
    },
    {
        'service_family': 'altar_consecration',
        'service_variant': 'main',
        'section': 'part_3',
        'reading_type': 'pauline',
        'raw_ref': 'Hebrews 13:10-16',
        'source_title': 'Rites of Consecration of Churches, Altars and Vessels',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Book-2_Consecration.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main Pauline in altar consecration section.',
    },
    {
        'service_family': 'altar_consecration',
        'service_variant': 'main',
        'section': 'part_3',
        'reading_type': 'psalm',
        'raw_ref': 'Psalm 23; Psalm 24; Psalm 26; Psalm 27; Psalm 85; Psalm 93',
        'source_title': 'Rites of Consecration of Churches, Altars and Vessels',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Book-2_Consecration.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'The altar consecration section explicitly gives a psalm set across the two incense offerings before the Pauline and Gospel.',
    },
    {
        'service_family': 'altar_consecration',
        'service_variant': 'main',
        'section': 'part_3',
        'reading_type': 'gospel',
        'raw_ref': 'Luke 19:1-10',
        'source_title': 'Rites of Consecration of Churches, Altars and Vessels',
        'source_url': 'https://saintbishoy.ca/wp-content/uploads/Rites_Book-2_Consecration.pdf',
        'source_page': SOURCE_ST_BISHOY_PAGE,
        'notes': 'Main Gospel in altar consecration section.',
    },
]


def ensure_dirs() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    if not DISABLE_VAULT_PUBLISH:
        VAULT.mkdir(parents=True, exist_ok=True)


def canonicalize_row_refs(row: Dict[str, str]) -> Dict[str, str]:
    row = dict(row)
    row['canonical_ref'] = canonicalize_text_ref(row['raw_ref'])
    return row


def build_passage_index(rows: List[Dict[str, str]]) -> List[Dict[str, str]]:
    out: List[Dict[str, str]] = []
    for row in rows:
        base = canonicalize_row_refs(row)
        seen = set()
        for seg in extract_text_ref_tokens(base['raw_ref']):
            normalized = canonicalize_text_ref(seg)
            if not normalized:
                continue
            key = (base['service_family'], base['service_variant'], base['section'], base['reading_type'], normalized)
            if key in seen:
                continue
            seen.add(key)
            out.append({
                'service_family': base['service_family'],
                'service_variant': base['service_variant'],
                'section': base['section'],
                'reading_type': base['reading_type'],
                'raw_ref': base['raw_ref'],
                'canonical_ref': base['canonical_ref'],
                'matched_ref': normalized,
                'source_title': base['source_title'],
                'source_url': base['source_url'],
                'source_page': base['source_page'],
                'notes': base['notes'],
                'source_kind': 'special_service',
            })
    return out


def write_csv(path: Path, rows: List[Dict[str, str]]) -> None:
    if not rows:
        path.write_text('', encoding='utf-8')
        return
    with path.open('w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def write_jsonl(path: Path, rows: List[Dict[str, str]]) -> None:
    with path.open('w', encoding='utf-8') as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + '\n')


def main() -> None:
    ensure_dirs()
    curated = [canonicalize_row_refs(r) for r in ROWS]
    pidx = build_passage_index(ROWS)
    write_csv(OUT / 'special_service_readings_curated.csv', curated)
    write_jsonl(OUT / 'special_service_readings_curated.jsonl', curated)
    write_csv(OUT / 'special_service_passage_index.csv', pidx)
    write_jsonl(OUT / 'special_service_passage_index.jsonl', pidx)
    if not DISABLE_VAULT_PUBLISH:
        write_csv(VAULT / 'special_service_readings_curated.csv', curated)
        write_csv(VAULT / 'special_service_passage_index.csv', pidx)
    print(json.dumps({'curated_rows': len(curated), 'passage_rows': len(pidx)}, indent=2))


if __name__ == '__main__':
    main()
